server:
    port: 9192
spring:
    h2:
        console:
            enabled: true
    application: order-service

#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/