server:
    port: 9191
spring:
    h2:
        console:
            enabled: true
    application: payment-service

#Eureka
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:9193/eureka/
    instance:
        hostname: localhost