server:
    port: 9191
spring:
    h2:
        console:
            enabled: true
    application: payment-service

#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/